{
 "title": "Cosmos Validators",
 "description": "Stats of a Cosmos validators set",
 "tags": [
  "cosmos",
  "blockchain"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validators_rank, chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "total validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "active validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"} > 0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "inactive validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"} == 0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "jailed validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_jailed{chain_id=\"$chain_id\"} > 0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "delegator shares",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_delegator_shares{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "commission",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sort_desc(count_values(\"value\", cosmos_validators_commission{chain_id=\"$chain_id\"} * 100))",
     "legendFormat": "{{ value }}%"
    }
   ]
  },
  {
   "title": "status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_status{chain_id=\"$chain_id\"} == 3)",
     "legendFormat": "bonded"
    },
    {
     "expr": "count(cosmos_validators_status{chain_id=\"$chain_id\"} == 2)",
     "legendFormat": "unbonding"
    },
    {
     "expr": "count(cosmos_validators_status{chain_id=\"$chain_id\"} == 1)",
     "legendFormat": "unbonded"
    }
   ]
  },
  {
   "title": "min self delegation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_min_self_delegation{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "tokens",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_tokens{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "min self delegation",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "count_values(\"value\", cosmos_validators_min_self_delegation{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "missed blocks",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 5)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  }
 ]
}